# Generated by Django 5.2.6 on 2025-09-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('labrador', 'Labrador Retriever'), ('golden_retriever', 'Golden Retriever'), ('german_shepherd', 'German Shepherd'), ('bulldog', 'Bulldog'), ('poodle', 'Poodle'), ('beagle', 'Beagle'), ('rottweiler', 'Rottweiler'), ('yorkshire_terrier', 'Yorkshire Terrier'), ('boxer', 'Boxer'), ('dachshund', 'Dachshund'), ('persian', 'Persian'), ('maine_coon', 'Maine Coon'), ('siamese', 'Siamese'), ('ragdoll', 'Ragdoll'), ('british_shorthair', 'British Shorthair'), ('abyssinian', 'Abyssinian'), ('bengal', 'Bengal'), ('russian_blue', 'Russian Blue'), ('scottish_fold', 'Scottish Fold'), ('domestic_shorthair', 'Domestic Shorthair'), ('parakeet', 'Parakeet'), ('canary', 'Canary'), ('cockatiel', 'Cockatiel'), ('lovebird', 'Lovebird'), ('macaw', 'Macaw'), ('african_grey', 'African Grey'), ('finch', 'Finch'), ('mixed_breed', 'Mixed Breed'), ('unknown', 'Unknown'), ('other_breed', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('guinea_pig', 'Guinea Pig'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('ferret', 'Ferret'), ('horse', 'Horse'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('pig', 'Pig'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='name',
            field=models.CharField(choices=[('dr_sarah_smith', 'Dr. Sarah Smith - Small Animal Specialist'), ('dr_michael_jones', 'Dr. Michael Jones - Exotic Animal Specialist'), ('dr_emily_davis', 'Dr. Emily Davis - Large Animal Specialist'), ('dr_robert_wilson', 'Dr. Robert Wilson - Surgery Specialist'), ('dr_lisa_brown', 'Dr. Lisa Brown - Emergency Care Specialist'), ('dr_james_taylor', 'Dr. James Taylor - Internal Medicine'), ('dr_amanda_white', 'Dr. Amanda White - Dermatology Specialist'), ('dr_david_miller', 'Dr. David Miller - Orthopedic Specialist')], max_length=150),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='specialization',
            field=models.CharField(choices=[('small_animals', 'Small Animals'), ('large_animals', 'Large Animals'), ('exotic_animals', 'Exotic Animals'), ('surgery', 'Surgery'), ('emergency_care', 'Emergency Care'), ('internal_medicine', 'Internal Medicine'), ('dermatology', 'Dermatology'), ('orthopedics', 'Orthopedics'), ('cardiology', 'Cardiology'), ('oncology', 'Oncology')], max_length=150),
        ),
    ]
