# Generated by Django 5.2.6 on 2025-09-16 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_pet_breed_alter_pet_species_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pet',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.pettype'),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
